// Package vision rewrites supported image content blocks.
package vision

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"hash"
	"net/http"
	"strings"

	"github.com/Euphie/llm-proxy/internal/llmrequest"
)

const descriptionPrefix = "[Image description generated by vision proxy]\n"

type imageRef struct {
	block        json.RawMessage
	sourceType   string
	cachePayload string
	taskContext  string
	imageURL     string
	fileID       string
	detail       string
	messageIndex int
	blockIndex   int
}

type protocolDocument struct {
	document *llmrequest.Document
	refs     []imageRef
}

func parseMessages(body []byte) (*protocolDocument, error) {
	return parseProtocolDocument(llmrequest.OperationAnthropicMessages, body)
}

func parseMessagesRoot(root map[string]json.RawMessage) (*protocolDocument, error) {
	return parseProtocolDocumentRoot(llmrequest.OperationAnthropicMessages, root)
}

func parseChatCompletions(body []byte) (*protocolDocument, error) {
	return parseProtocolDocument(llmrequest.OperationOpenAIChatCompletions, body)
}

func parseChatCompletionsRoot(root map[string]json.RawMessage) (*protocolDocument, error) {
	return parseProtocolDocumentRoot(llmrequest.OperationOpenAIChatCompletions, root)
}

func parseResponses(body []byte) (*protocolDocument, error) {
	return parseProtocolDocument(llmrequest.OperationOpenAIResponses, body)
}

func parseResponsesRoot(root map[string]json.RawMessage) (*protocolDocument, error) {
	return parseProtocolDocumentRoot(llmrequest.OperationOpenAIResponses, root)
}

func parseProtocolDocument(operation llmrequest.Operation, body []byte) (*protocolDocument, error) {
	document, err := llmrequest.Parse(operation, body)
	if err != nil {
		return nil, err
	}
	return adaptProtocolDocument(document), nil
}

func parseProtocolDocumentRoot(
	operation llmrequest.Operation,
	root map[string]json.RawMessage,
) (*protocolDocument, error) {
	document, err := llmrequest.ParseRoot(operation, root)
	if err != nil {
		return nil, err
	}
	return adaptProtocolDocument(document), nil
}

func adaptProtocolDocument(document *llmrequest.Document) *protocolDocument {
	images := document.Images()
	refs := make([]imageRef, len(images))
	for index, image := range images {
		refs[index] = imageRef{
			block:        image.Block,
			sourceType:   visionSourceType(image.SourceKind),
			cachePayload: image.CachePayload,
			taskContext:  boundTaskContext(image.TaskContext),
			imageURL:     image.ImageURL,
			fileID:       image.FileID,
			detail:       image.Detail,
			messageIndex: image.NodeIndex,
			blockIndex:   image.BlockIndex,
		}
	}
	return &protocolDocument{document: document, refs: refs}
}

func visionSourceType(kind llmrequest.ImageSourceKind) string {
	switch kind {
	case llmrequest.ImageSourceFileID:
		return "file"
	default:
		return string(kind)
	}
}

func (d *protocolDocument) images() []imageRef {
	return append([]imageRef(nil), d.refs...)
}

func (d *protocolDocument) rewrite(descriptions []string) ([]byte, error) {
	if len(descriptions) != len(d.refs) {
		return nil, fmt.Errorf(
			"image descriptions count %d does not match images count %d",
			len(descriptions), len(d.refs),
		)
	}
	replacements := make([]string, len(descriptions))
	for index := range descriptions {
		replacements[index] = replacementPrefix(d.refs[index]) + descriptions[index]
	}
	return d.document.RewriteImages(replacements)
}

func parseDescription(body []byte) (string, error) {
	var response struct {
		Content []struct {
			Type string `json:"type"`
			Text string `json:"text"`
		} `json:"content"`
	}
	if err := json.Unmarshal(body, &response); err != nil {
		return "", fmt.Errorf("parse vision response: %w", err)
	}
	var texts []string
	for _, block := range response.Content {
		if block.Type == "text" && strings.TrimSpace(block.Text) != "" {
			texts = append(texts, block.Text)
		}
	}
	if len(texts) == 0 {
		return "", fmt.Errorf("vision response contains no text")
	}
	return strings.Join(texts, "\n"), nil
}

func imageCacheKey(provider, model, prompt string, image imageRef) string {
	hash := sha256.New()
	for _, value := range []string{provider, model, prompt, image.sourceType, image.cachePayload} {
		writeFramedString(hash, value)
	}
	return hex.EncodeToString(hash.Sum(nil))
}

func scopedImageCacheKey(
	secret []byte,
	headers http.Header,
	forwardedHeaders []string,
	provider, model, prompt string,
	image imageRef,
) string {
	mac := hmac.New(sha256.New, secret)
	writeUint64(mac, uint64(len(forwardedHeaders)))
	for _, name := range forwardedHeaders {
		writeFramedString(mac, name)
		values := headers.Values(name)
		writeUint64(mac, uint64(len(values)))
		for _, value := range values {
			writeFramedString(mac, value)
		}
	}
	writeFramedString(mac, imageCacheKey(provider, model, prompt, image))
	return hex.EncodeToString(mac.Sum(nil))
}

func writeFramedString(dst hash.Hash, value string) {
	writeUint64(dst, uint64(len(value)))
	_, _ = dst.Write([]byte(value))
}

func writeUint64(dst hash.Hash, value uint64) {
	var encoded [8]byte
	binary.BigEndian.PutUint64(encoded[:], value)
	_, _ = dst.Write(encoded[:])
}
