// Package vision parses and rewrites Anthropic image content blocks.
package vision

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"hash"
	"net/http"
	"strings"
)

const descriptionPrefix = "[Image description generated by vision proxy]\n"

type imageRef struct {
	block        json.RawMessage
	sourceType   string
	cachePayload string
	messageIndex int
	blockIndex   int
}

type messageNode struct {
	fields       map[string]json.RawMessage
	content      []json.RawMessage
	arrayContent bool
}

type messageDocument struct {
	root      map[string]json.RawMessage
	messages  []messageNode
	imageRefs []imageRef
}

func parseMessages(body []byte) (*messageDocument, error) {
	var root map[string]json.RawMessage
	if err := json.Unmarshal(body, &root); err != nil {
		return nil, fmt.Errorf("parse request: %w", err)
	}
	if root == nil {
		return nil, fmt.Errorf("request must be an object")
	}

	messagesRaw, ok := root["messages"]
	if !ok {
		return nil, fmt.Errorf("request messages is required")
	}
	if !isJSONType(messagesRaw, '[') {
		return nil, fmt.Errorf("request messages must be an array")
	}
	var rawMessages []json.RawMessage
	if err := json.Unmarshal(messagesRaw, &rawMessages); err != nil {
		return nil, fmt.Errorf("parse messages: %w", err)
	}

	doc := &messageDocument{root: root, messages: make([]messageNode, 0, len(rawMessages))}
	for messageIndex, rawMessage := range rawMessages {
		if !isJSONType(rawMessage, '{') {
			return nil, fmt.Errorf("message %d must be an object", messageIndex)
		}
		var fields map[string]json.RawMessage
		if err := json.Unmarshal(rawMessage, &fields); err != nil {
			return nil, fmt.Errorf("parse message %d: %w", messageIndex, err)
		}
		node := messageNode{fields: fields}
		if content, ok := fields["content"]; ok {
			switch {
			case isJSONType(content, '"'):
				var text string
				if err := json.Unmarshal(content, &text); err != nil {
					return nil, fmt.Errorf("parse message %d content: %w", messageIndex, err)
				}
			case isJSONType(content, '['):
				if err := json.Unmarshal(content, &node.content); err != nil {
					return nil, fmt.Errorf("parse message %d content: %w", messageIndex, err)
				}
				node.arrayContent = true
				for blockIndex, block := range node.content {
					image, ok, err := parseImageBlock(block, messageIndex, blockIndex)
					if err != nil {
						return nil, err
					}
					if ok {
						doc.imageRefs = append(doc.imageRefs, image)
					}
				}
			default:
				return nil, fmt.Errorf("message %d content must be a string or array", messageIndex)
			}
		}
		doc.messages = append(doc.messages, node)
	}
	return doc, nil
}

func (d *messageDocument) images() []imageRef {
	return d.imageRefs
}

func parseImageBlock(block json.RawMessage, messageIndex, blockIndex int) (imageRef, bool, error) {
	if !isJSONType(block, '{') {
		return imageRef{}, false, nil
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(block, &fields); err != nil {
		return imageRef{}, false, fmt.Errorf("parse message %d content block %d: %w", messageIndex, blockIndex, err)
	}
	blockTypeRaw, ok := fields["type"]
	if !ok {
		return imageRef{}, false, nil
	}
	var blockType string
	if err := json.Unmarshal(blockTypeRaw, &blockType); err != nil || blockType != "image" {
		return imageRef{}, false, nil
	}
	sourceRaw, ok := fields["source"]
	if !ok || !isJSONType(sourceRaw, '{') {
		return imageRef{}, false, fmt.Errorf("message %d content block %d image source must be an object", messageIndex, blockIndex)
	}
	var source map[string]json.RawMessage
	if err := json.Unmarshal(sourceRaw, &source); err != nil {
		return imageRef{}, false, fmt.Errorf("parse message %d content block %d image source: %w", messageIndex, blockIndex, err)
	}
	sourceType, present, err := requiredString(source, "type")
	if err != nil || !present {
		return imageRef{}, false, fmt.Errorf("message %d content block %d image source type is required", messageIndex, blockIndex)
	}

	image := imageRef{block: block, sourceType: sourceType, messageIndex: messageIndex, blockIndex: blockIndex}
	switch sourceType {
	case "base64":
		mediaType, err := nonEmptyString(source, "media_type")
		if err != nil {
			return imageRef{}, false, imageFieldError(messageIndex, blockIndex, sourceType, err)
		}
		data, err := nonEmptyString(source, "data")
		if err != nil {
			return imageRef{}, false, imageFieldError(messageIndex, blockIndex, sourceType, err)
		}
		image.cachePayload = mediaType + "\x00" + data
	case "url":
		url, err := nonEmptyString(source, "url")
		if err != nil {
			return imageRef{}, false, imageFieldError(messageIndex, blockIndex, sourceType, err)
		}
		image.cachePayload = url
	case "file":
		fileID, err := nonEmptyString(source, "file_id")
		if err != nil {
			return imageRef{}, false, imageFieldError(messageIndex, blockIndex, sourceType, err)
		}
		image.cachePayload = fileID
	default:
		return imageRef{}, false, fmt.Errorf("message %d content block %d has unsupported image source type %q", messageIndex, blockIndex, sourceType)
	}
	return image, true, nil
}

func (d *messageDocument) rewrite(descriptions []string) ([]byte, error) {
	if len(descriptions) != len(d.imageRefs) {
		return nil, fmt.Errorf("image descriptions count %d does not match images count %d", len(descriptions), len(d.imageRefs))
	}
	replacements := make(map[[2]int]json.RawMessage, len(d.imageRefs))
	for imageIndex, image := range d.imageRefs {
		replacement, err := json.Marshal(map[string]string{
			"type": "text",
			"text": descriptionPrefix + descriptions[imageIndex],
		})
		if err != nil {
			return nil, fmt.Errorf("marshal image description %d: %w", imageIndex, err)
		}
		replacements[[2]int{image.messageIndex, image.blockIndex}] = replacement
	}

	rawMessages := make([]json.RawMessage, len(d.messages))
	for messageIndex, node := range d.messages {
		fields := node.fields
		if node.arrayContent {
			content := append([]json.RawMessage(nil), node.content...)
			changed := false
			for blockIndex := range content {
				if replacement, ok := replacements[[2]int{messageIndex, blockIndex}]; ok {
					content[blockIndex] = replacement
					changed = true
				}
			}
			if changed {
				var err error
				fields = cloneRawFields(node.fields)
				fields["content"], err = json.Marshal(content)
				if err != nil {
					return nil, fmt.Errorf("marshal message %d content: %w", messageIndex, err)
				}
			}
		}
		encoded, err := json.Marshal(fields)
		if err != nil {
			return nil, fmt.Errorf("marshal message %d: %w", messageIndex, err)
		}
		rawMessages[messageIndex] = encoded
	}

	root := cloneRawFields(d.root)
	var err error
	root["messages"], err = json.Marshal(rawMessages)
	if err != nil {
		return nil, fmt.Errorf("marshal messages: %w", err)
	}
	result, err := json.Marshal(root)
	if err != nil {
		return nil, fmt.Errorf("marshal rewritten request: %w", err)
	}
	return result, nil
}

func parseDescription(body []byte) (string, error) {
	var response struct {
		Content []struct {
			Type string `json:"type"`
			Text string `json:"text"`
		} `json:"content"`
	}
	if err := json.Unmarshal(body, &response); err != nil {
		return "", fmt.Errorf("parse vision response: %w", err)
	}
	var texts []string
	for _, block := range response.Content {
		if block.Type == "text" && strings.TrimSpace(block.Text) != "" {
			texts = append(texts, block.Text)
		}
	}
	if len(texts) == 0 {
		return "", fmt.Errorf("vision response contains no text")
	}
	return strings.Join(texts, "\n"), nil
}

func imageCacheKey(provider, model, prompt string, image imageRef) string {
	hash := sha256.New()
	for _, value := range []string{provider, model, prompt, image.sourceType, image.cachePayload} {
		writeFramedString(hash, value)
	}
	return hex.EncodeToString(hash.Sum(nil))
}

func scopedImageCacheKey(
	secret []byte,
	headers http.Header,
	provider, model, prompt string,
	image imageRef,
) string {
	mac := hmac.New(sha256.New, secret)
	writeUint64(mac, uint64(len(forwardedHeaders)))
	for _, name := range forwardedHeaders {
		writeFramedString(mac, name)
		values := headers.Values(name)
		writeUint64(mac, uint64(len(values)))
		for _, value := range values {
			writeFramedString(mac, value)
		}
	}
	writeFramedString(mac, imageCacheKey(provider, model, prompt, image))
	return hex.EncodeToString(mac.Sum(nil))
}

func writeFramedString(dst hash.Hash, value string) {
	writeUint64(dst, uint64(len(value)))
	_, _ = dst.Write([]byte(value))
}

func writeUint64(dst hash.Hash, value uint64) {
	var encoded [8]byte
	binary.BigEndian.PutUint64(encoded[:], value)
	_, _ = dst.Write(encoded[:])
}

func requiredString(fields map[string]json.RawMessage, name string) (string, bool, error) {
	raw, ok := fields[name]
	if !ok {
		return "", false, nil
	}
	var value string
	if err := json.Unmarshal(raw, &value); err != nil {
		return "", true, fmt.Errorf("%s must be a string", name)
	}
	return value, true, nil
}

func nonEmptyString(fields map[string]json.RawMessage, name string) (string, error) {
	value, ok, err := requiredString(fields, name)
	if err != nil {
		return "", err
	}
	if !ok || value == "" {
		return "", fmt.Errorf("%s is required", name)
	}
	return value, nil
}

func imageFieldError(messageIndex, blockIndex int, sourceType string, err error) error {
	return fmt.Errorf("message %d content block %d image source %s: %w", messageIndex, blockIndex, sourceType, err)
}

func cloneRawFields(fields map[string]json.RawMessage) map[string]json.RawMessage {
	clone := make(map[string]json.RawMessage, len(fields))
	for name, value := range fields {
		clone[name] = value
	}
	return clone
}

func isJSONType(raw json.RawMessage, first byte) bool {
	raw = json.RawMessage(strings.TrimSpace(string(raw)))
	return len(raw) > 0 && raw[0] == first
}
